version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  artifacts:
  files:
    - ls -l
    - target/order-service.jar
  discard-paths: yes
