version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/orderservice.jar
  discard-paths: yes
